# Generated by Django 2.2.6 on 2020-01-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_address',
            field=models.CharField(default='Not available', max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='book_contact',
            field=models.IntegerField(default=0),
        ),
    ]
